### ISSUE TITLE
Automatically start watching newly added directories

### ISSUE THREAD

**Issue by geek876** [unbalanced/grunt-simple-watch#9]
watch: {
                        sass: {
                                files: ['/<dir>/**/*.scss'],
                                tasks: ['sass:dist']
                        }
                },

If I add another directory like dir/dir1, will it pick it up the change ? Until now, I have been using grunt-contrib-sass and that does'nt seem to pick it up new directories, until you restart the grunt task.

**Comment by obzenner** [comment]
@geek876 I tried this with this config:
```

		slackTestSpecs: {
			files: [
				'public/javascripts/**/*.js'
			],
			tasks: [
				'testtask'
			],
			options: {
				spawn: false,
				event: ['deleted', 'added']
			}
		}
```

...and it worked with newly created directories but for some reason it does not trigger the `testtask` for me for `deleted` event. @unbalanced have you encountered something like this?

**Comment by obzenner** [comment]
@unbalanced I believe the issue with `delete` might be here https://github.com/unbalanced/grunt-simple-watch/blob/master/tasks/simple_watch.js#L116
Should I open an new issue?

**Comment by szurcher** [comment]
I ran into this problem where deleting files did not cause watch to trigger the task run despite it noticing the files were deleted.  It is because of https://github.com/unbalanced/grunt-simple-watch/blob/master/tasks/simple_watch.js#L101 where the only trigger for tasks is if the filepath is in the intersection of the changedFiles and target.files array.  As the file was deleted, it will NOT be in the target.files array and so will not appear in the intersection.  If you only have deleted files in a watch interval, then, the watch will not trigger watch tasks as the intersection will be empty.  I patched the code like so:
```
--- node_modules/grunt-simple-watch/tasks/simple_watch.js       2016-09-06 11:32:16.682014000 -1000
+++ ./simple_watch.js   2016-09-06 11:31:48.890014000 -1000
@@ -99,8 +99,9 @@
                        targets.forEach(function(target) {
                                var files = grunt.file.expand(target.files);
                                var intersection = grunt.util._.intersection(fileArray, files);
+        var difference = grunt.util._.difference(fileArray, files);
                                // Enqueue specified tasks if a matching file was found.
-                               if ( intersection.length > 0 && target.tasks) {
+                               if ( (intersection.length > 0 || difference.length > 0) && target.tasks) {
                                        grunt.task.run(target.tasks).mark();
                                }
                        });
```
So now if the filepath appears only in the changedFiles array it will also trigger the tasks to run.

**Comment by unbalanced** [comment]
Merged it. Thanks @szurcher :)
Can you guys please take a close look?
